Rename a function due to conflict
Fatal error: Cannot redeclare get_template_id() (previously declared in /var/www/html/wp-content/plugins/acf-product-review-1/block-templates/roundup-reviews.php:8) in /var/www/html/wp-content/plugins/acf-product-review-1/block-templates/roundup-reviews.php on line 8